2023-05-29 10:48:10,388 - qtpyvcp - INFO - Logging to /home/groot/linuxcnc/configs/grootbasic/sim.log
2023-05-29 10:48:10,388 - qtpyvcp - INFO - QtPyVCP Version: python3_master+286.g54a2a9e4
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - Machine appearers to be a gantry config having a double Y axis
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - The machine has 4 axes and 5 joints
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - The Axis/Joint mapping is:
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - Axis X --> Joint 0
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - Axis Y0 --> Joint 1
2023-05-29 10:48:11,047 - qtpyvcp.utilities.info - INFO - Axis Y1 --> Joint 2
2023-05-29 10:48:11,048 - qtpyvcp.utilities.info - INFO - Axis Z --> Joint 3
2023-05-29 10:48:11,048 - qtpyvcp.utilities.info - INFO - Axis A --> Joint 4
2023-05-29 10:48:11,240 - qtpyvcp - INFO - Loading global stylesheet: /home/groot/dev/probe_basic/probe_basic/probe_basic.qss
2023-05-29 10:48:14,811 - qtpyvcp.app.launcher - INFO - Loading POSTGUI_HALFILE: /home/groot/linuxcnc/configs/grootbasic/hallib/postgui.hal
2023-05-29 10:48:14,992 - qtpyvcp.plugins.notifications - ERROR - Warning TLS overtravel
2023-05-29 10:48:15,351 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:15,378 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:16,892 - qtpyvcp.actions.machine_actions - INFO - Homing all axes
2023-05-29 10:48:21,179 - qtpyvcp.plugins.tool_table - INFO - Reloading tool in spindle: 340
2023-05-29 10:48:21,380 - qtpyvcp.actions.base_actions - ERROR - Can't set mode while machine is running
2023-05-29 10:48:21,380 - qtpyvcp.actions.machine_actions - ERROR - Failed to issue MDI command: M61 Q340 G43
2023-05-29 10:48:25,305 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:25,330 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:25,486 - qtpyvcp.widgets.input_widgets.file_system - INFO - File encoding: ascii
2023-05-29 10:48:25,714 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:25,727 - qtpyvcp.app.launcher - CRITICAL - Unhandled exception in vtk_backplot.py line 444
Traceback (most recent call last):
  File "/home/groot/dev/qtpyvcp/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py", line 444, in load_program
    self.load(fname)
  File "/home/groot/dev/qtpyvcp/qtpyvcp/widgets/display_widgets/vtk_backplot/base_backplot.py", line 75, in load
    self.notification.setNotify("3D plot", "Error in {} line {}\n{}".format(fname, seq - 1, msg))
AttributeError: 'Notifications' object has no attribute 'setNotify'
2023-05-29 10:48:35,400 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:41,761 - qtpyvcp.widgets.input_widgets.file_system - INFO - File encoding: ascii
2023-05-29 10:48:42,028 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
2023-05-29 10:48:42,067 - qtpyvcp.app.launcher - CRITICAL - Unhandled exception in vtk_backplot.py line 444
Traceback (most recent call last):
  File "/home/groot/dev/qtpyvcp/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py", line 444, in load_program
    self.load(fname)
  File "/home/groot/dev/qtpyvcp/qtpyvcp/widgets/display_widgets/vtk_backplot/base_backplot.py", line 75, in load
    self.notification.setNotify("3D plot", "Error in {} line {}\n{}".format(fname, seq - 1, msg))
AttributeError: 'Notifications' object has no attribute 'setNotify'
2023-05-29 10:48:51,820 - qtpyvcp.widgets.input_widgets.gcode_text_edit - INFO - File encoding: ascii
